name: Containers Deploy

on:
  workflow_run:
    workflows: ["Docker tests"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-dockers:
    runs-on: ubuntu-latest
#    if: |
#      github.event.workflow_run.conclusion == 'success' &&
#      startsWith(github.event.workflow_run.head_branch, 'refs/tags/') &&
#      contains(github.event.workflow_run.head_branch, 'refs/tags/v') &&
#      github.event.workflow_run.head_branch =~ 'refs/tags/v[0-9]+\\.[0-9]+\\.[0-9]+$'

    strategy:
      fail-fast: false                 # Ensures all combinations run, even if one fails
      matrix:
        pgversion: [16, 17]              # Tmp while debugging
#        pgversion: [13, 14, 15, 16, 17]  # List of PostgreSQL versions
    env:
      PGVERSION: ${{ matrix.pgversion }}  # Set PGVERSION for each job

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-pg${{ matrix.pgversion }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: PGVERSION=${{ matrix.pgversion }}
